// scripts/deploy.js
// ============================================================
// Script untuk deploy MedicalRecordVault ke jaringan Ethereum
// ============================================================
// Penggunaan:
//   Local:   npx hardhat run scripts/deploy.js
//   Sepolia: npx hardhat run scripts/deploy.js --network sepolia
// ============================================================

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("=".repeat(60));
    console.log("  DEPLOYING MedicalRecordVault");
    console.log("=".repeat(60));

    // Ambil informasi deployer
    const [deployer] = await hre.ethers.getSigners();
    console.log(`\n📋 Deployer address: ${deployer.address}`);

    const balance = await hre.ethers.provider.getBalance(deployer.address);
    console.log(`💰 Deployer balance: ${hre.ethers.formatEther(balance)} ETH`);

    // Deploy kontrak
    console.log("\n⏳ Deploying contract...");
    const vault = await hre.ethers.deployContract("MedicalRecordVault");
    await vault.waitForDeployment();

    const contractAddress = await vault.getAddress();

    console.log("\n✅ MedicalRecordVault deployed successfully!");
    console.log(`📍 Contract address: ${contractAddress}`);
    console.log(`🔗 Network: ${hre.network.name}`);

    if (hre.network.name === "sepolia") {
        console.log(
            `🔎 Etherscan: https://sepolia.etherscan.io/address/${contractAddress}`
        );
    }

    // ============================================================
    // Auto-generate frontend/.env with contract address
    // Preserves existing Pinata config if .env already exists
    // ============================================================
    const envPath = path.join(__dirname, "..", "frontend", ".env");

    // Read existing env vars to preserve Pinata config
    let existingVars = {};
    try {
        if (fs.existsSync(envPath)) {
            const existing = fs.readFileSync(envPath, "utf-8");
            existing.split("\n").forEach((line) => {
                const trimmed = line.trim();
                if (trimmed && !trimmed.startsWith("#")) {
                    const [key, ...valParts] = trimmed.split("=");
                    if (key) existingVars[key.trim()] = valParts.join("=").trim();
                }
            });
        }
    } catch (_) { }

    const pinataJwt = existingVars.VITE_PINATA_JWT || "";
    const pinataGateway = existingVars.VITE_PINATA_GATEWAY || "https://gateway.pinata.cloud";

    const envContent = `# Auto-generated by deploy.js — ${new Date().toISOString()}
# Network: ${hre.network.name}
VITE_CONTRACT_ADDRESS=${contractAddress}

# Pinata IPFS Configuration
# Dapatkan JWT dari: https://app.pinata.cloud/developers/api-keys
VITE_PINATA_JWT=${pinataJwt}
VITE_PINATA_GATEWAY=${pinataGateway}
`;

    try {
        fs.writeFileSync(envPath, envContent, "utf-8");
        console.log(`\n📝 frontend/.env telah diupdate dengan contract address`);
        console.log(`   → ${envPath}`);
        if (!pinataJwt) {
            console.log(`\n⚠️  VITE_PINATA_JWT belum diset!`);
            console.log(`   Edit frontend/.env dan tambahkan Pinata JWT Anda.`);
        }
        console.log(`\n⚠️  Jika frontend sedang berjalan, RESTART dev server:`);
        console.log(`   cd frontend && npm run dev`);
    } catch (err) {
        console.log(`\n⚠️  Gagal menulis .env otomatis: ${err.message}`);
        console.log(`   Silakan buat file frontend/.env secara manual:`);
        console.log(`   VITE_CONTRACT_ADDRESS=${contractAddress}`);
    }

    console.log("\n" + "=".repeat(60));
    console.log("  DEPLOYMENT COMPLETE");
    console.log("=".repeat(60));

    return contractAddress;
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("\n❌ Deployment failed:");
        console.error(error);
        process.exit(1);
    });
